CREATE DATABASE IF NOT EXISTS calculador_imc
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE calculador_imc;

CREATE TABLE IF NOT EXISTS registros_imc (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NULL,
    peso DECIMAL(5,2) NOT NULL,
    altura DECIMAL(3,2) NOT NULL,
    imc DECIMAL(5,2) NOT NULL,
    classificacao VARCHAR(30) NOT NULL,
    data_calculo DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
